# backend/app/schemas/query.py
from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

# --- Phase 1: VizSpec Definition (The LLM output instruction) ---
class VizSpec(BaseModel):
    """Defines the visualization configuration generated by the LLM."""
    type: str = Field(..., description="Chart type: line|bar|scatter|heatmap|text.")
    x: str = Field(..., description="Column for the X-axis.")
    y: str = Field(..., description="Column for the Y-axis.")
    title: str = Field("Generated Chart", description="Title for the plot.")
    aggregation: str = Field("none", description="SQL aggregation used: sum|avg|count|none.")

# --- Phase 1: NL Request Submission (Input) ---
class AnalyzeRequest(BaseModel):
    """The data structure for the POST /analyze request."""
    prompt: str = Field(..., description="The natural language command from the user.")
    context_tables: List[str] = Field(["sales", "users"], description="Tables the LLM should be allowed to access.")

# --- Phase 1: API Response (The Preview/Safety Check) ---
class AnalyzeResponse(BaseModel):
    """The data structure for the POST /analyze response (Phase 1 output)."""
    job_id: str
    generated_sql: str
    sql_params: Dict[str, Any]
    viz_spec: VizSpec
    preview_rows: List[Dict[str, Any]]
    needs_clarification: bool = False
    missing_info_question: Optional[str] = None # Added for explicit clarification text

# --- Phase 2: Execution Submission (Input) ---
class ExecuteRequest(BaseModel):
    """The data structure for the POST /execute request."""
    job_id: str
    confirmed: bool = True

# --- Phase 2: Final Result (Output) ---
class JobResult(BaseModel):
    """The data structure for the POST /execute response (Final chart delivery)."""
    status: str
    chart_url: Optional[str] = None
    data_summary: Optional[Dict[str, Any]] = None