from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class VizSpec(BaseModel):
    """Defines the visualization configuration generated by the LLM."""
    type: str = Field(..., description="Chart type: line|bar|scatter|heatmap|text.")
    x: str = Field(..., description="Column for the X-axis.")
    y: str = Field(..., description="Column for the Y-axis.")
    title: str = Field("Generated Chart", description="Title for the plot.")
    aggregation: str = Field("none", description="SQL aggregation used: sum|avg|count|none.")

class AnalyzeRequest(BaseModel):
    """The data structure for the POST /analyze request."""
    prompt: str = Field(..., description="The natural language command from the user.")
    context_tables: List[str] = Field(["sales", "users"], description="Tables the LLM should be allowed to access.")

class AnalyzeResponse(BaseModel):
    """The data structure for the POST /analyze response (Phase 1 output)."""
    job_id: str
    generated_sql: str
    sql_params: Dict[str, Any]
    viz_spec: VizSpec
    preview_rows: List[Dict[str, Any]]
    needs_clarification: bool = False
    missing_info_question: Optional[str] = None 

class ExecuteRequest(BaseModel):
    """The data structure for the POST /execute request."""
    job_id: str
    confirmed: bool = True

class JobResult(BaseModel):
    """The data structure for the POST /execute response (Final chart delivery)."""
    status: str
    chart_url: Optional[str] = None
    data_summary: Optional[Dict[str, Any]] = None